# Generated by Django 3.0 on 2021-04-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
