# Generated by Django 3.0 on 2021-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
